# Generated by Django 4.2.4 on 2023-11-05 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_teacherdetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignmentname', models.CharField(max_length=255)),
                ('assignmentdetails', models.CharField(max_length=255)),
                ('classdetails', models.CharField(max_length=255)),
            ],
        ),
    ]
